name: Docker Image CI

on:
  push:
    branches: [ "v7" ]
  pull_request:
    branches: [ "v7" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t edm115/unzip-bot .
    - name: Run Docker container
      run: docker run --rm edm115/unzip-bot
